### ISSUE TITLE
Cant authorize

### ISSUE THREAD

**Issue by jacobhallgren** [bradymholt/smartthings-rest-api#2]
I get stuck on the step run: open: https://graph.api.smartthings.com/oauth/authorize?response_type=code&client_id=XXXX&scope=app&redirect_uri=http://localhost

It gives me Authorizing the selected devices failed; please try again later or contact support@smartthings.com

And Please select at least one device to authorize

But I cant select a device to authorize. Any suggestions?

Thanks.

**Comment by mirraj2** [comment]
I had the same problem, then did it in incognito and it worked.

**Comment by MB-Jan** [comment]
Same issue here and incognito mode does not work (tried with Chrome and Firefox)
